server:
  port: 9091
spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/microservice_level_1
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true