server:
  port: 9093
spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/microservice_level_1_comment
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true