server:
  port: 9092
spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/microservice_level_1_blog_post
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true